language: python
python:
        - '3.6'

branches:
        only:
                - nwadd

before_script:
        - pip install -r requirements.txt

services:
        - postgresql

env: DJANGO_SETTINGS_MODULE="OCprojetHuit.settings.travis"

script:
        - python ./manage.py test
