language: python
python:
        - '3.6'

branches:
        only:
                - nwadd

before_script:
        - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="OCprojetHuit.settings"

services:
        - postgresql

script:
        - ./manage.py test
